---
title: "Blogging with Github and RStudio"
author: "Auke Hoekstra"
date: "24 juli 2015"
output: 
  html_document:
    theme: spacelab
---



## Setting up your Github pages

<jekyllrb.com> is supposed to be the comprehensive reference for this. 
I followed along with this [video by Brad Westfall](https://youtu.be/nN6QuNqmAwk).

### Make powershell default
First I made powershell the default command line on my windows machine. Simply install powershell and run the [first script on this page](http://blogs.interfacett.com/how-make-powershell-default-console-windows-server-core). It can do everything cmd.exe does but it can do much more and has the convenience that it supports cut and paste.

### Create a hello world page
Then I opened github for windows and using the gearwheel opened the github shell. Powershell opened for me in the right directory (github root). Then I typed:

    mkdir evflex        # to create a directory
    cd blog             # go into the directory
    git init            # to create the repo (.git files) here
    touch index.html    # to create the index file that github will look for

For testing an empty index.html file is not optimal. So I opened it in an editor (like atom or notepad) and typed:

    <HTML>
       <HEAD>
          <TITLE>
             evflex says hello
          </TITLE>
       </HEAD>
    <BODY>
       <H1>evflex are go</H1>
       <P>Hello evflex readers!</P>
    </BODY>
    </HTML>

I saved my changes, closed the editor and switched back to powershell. I added the file and made my initial commit:

    git add .
    git commit -m "init"

Then I went to github.com to create the remote repo on github. I chose create new repo, typed in evflex, unchecked "make readme.md" and on the next page there was a command for when you already have a local repo. This I pasted into my local powershell with rightclick:

    git remote add origin git@github.com:AukeHoekstra/evflex.git
    git push -u origin master

This tells the local repo where to find its remote repo on github and it pushes the first content (the index.html file) to the remote repo.

Finally I created a branch called gh-pages. This special branch is where the Jekyll server on github.com will be looking for new content. From this branche I pushed the index.html page to github:

    git branch gh-pages
    git push origin gh-pages

That is basically it. After a few minutes (it can take hours) I surfed to the following location to admire my message to the world:

    aukehoekstra.github.io/evflex.

### Connect evflex.github.io to evflex.org
Buy .org and .com, .net, .nl and .eu.
Redirect .org to github.
Redirect .com, .net, .nl and .eu to .org.

The video says to create a file called "CNAME" with as content just the URL where you want to point from. E.g. evflex.org. Then:

    git add . 
    git commit -m "cname"
    git checkout gh-pages # switches you to the gh-pages branch
    git merge master # merges cname file of the master into gh-pages
    git push --set-upstream origin gh-pages
    git push # puts the content of gh-pages on github

The first time I failed because the video did not prompt me to set the upstream branch. But this worked so to check I went to github.com, refreshed the page and saw that CNAME showed up in the branch.

Another problem I ran into was that github kept warning me that it had added Github (RSA) to the list of known hosts. Jeremiah Gowdy came up with [the solution on stackoverflow](http://stackoverflow.com/questions/9299651/warning-permanently-added-to-the-list-of-known-hosts-message-from-git): go to users\Auke\.ssh and add a file called config with the line "UserKnownHostsFile ~/.ssh/known_hosts". Problem solved.

The final step is to tell the registrar to point to Github. In my case this is Byte.nl. So I surfed to their service panels DNS settings and create the following records:

    evflex.org, type A, content 192.30.252.153
    evflex.org, type A, content 192.30.252.154
    www.evflex.org, type CNAME, content evflex.org

This can take up to 24 hours but within a minute I could type <evflex.org> and <www.evflex.org> and I was taken directly to my Hello world page at aukehoekstra.github.io/evflex without me (or my reader) noticing.

## Install Jekyll
Windows is not officially supported (?) but I was directed to <http://jekyll-windows.juthilo.com/>. This site told me to to to <http://rubyinstaller.org/downloads/> and install Ruby and the Devkit (like DevKit-mingw64). I had to restart the computer before I could give the following commands in powershell:

    cd c:\Ruby22-x64start
    ruby dk.rb init 
    ruby dk.rb install

Then I installed Python version 2 (!). Don't forget to choose "add python.exe to path" as a complete install on the harddrive. This will also give you pip. Finally we do:

    gem install jekyll # takes a while
    cd c:\users\auke\github
    jekyll new blog # lots of files into the blog
    cd blog
    jekyll serve

## Understand Jekyll themes

### File structure
The Jekyll bootrap site [describes how Jekyll works](http://themes.jekyllbootstrap.com/preview/twitter/lessons/2011/12/29/jekyll-introduction/). Your website should look like this:

  * _config.yml: stores configuration data.

  * _includes: this folder is for partial views.

  * _layouts: this folder is for the main templates your content will be inserted into. You can have different layouts for different pages or page sections.

  * _posts: this folder contains your dynamic content/posts. the naming format is required to be @YEAR-MONTH-DATE-title.MARKUP@.

  * _site: this is where the generated site will be placed once Jekyll is done transforming it.

  * assets: this folder is not part of the standard jekyll structure. The assets folder represents any generic folder you happen to create in your root directory. Directories and files not properly formatted for jekyll will be left untouched for you to serve normally.

### Yihui's knitr template












## Play around with Jekyll themes

## Turn the .Rmd files into .md files

## Add .md files to your Jekyll site

## Automate the process from .Rmd to published .md on Jekyll






# Guys and gals who have been there

<https://github.com/yihui/knitr-jekyll> who build knitr gives us an example of a Jekyll based website using knitr and R Markdown. The idea is to serve the files locally and push them to the gh-pages branch of your Github repo when you are satisfied







[John Zelner is auto-generating blog posts in R Markdown with jekyll and knitr](http://www.jonzelner.net/jekyll/knitr/r/2014/07/02/autogen-knitr/) on 02 July 2014. Mixing Markdown (and TeX) with R using Knitr is a joy, and even more so when you can auto-generate your results and view them live as you save changes.

John has set it up in the following way:

  * He saves his .Rmd file to a _knitr directory in the root of his Jekyll site.
  * There is an auto executing render_post.R script that watches for incoming files and re-knits the .Rmd file into vanilla markdown and copies it to the _posts directory. 
  * 

[Nicole White](https://github.com/nicolewhite/nicolewhite.github.io/blob/master/_posts/2015-02-07-r-blogging-with-rmarkdown-knitr-jekyll.md) also has a description.




[Automated Knitr In Jekyll](http://www.carlboettiger.info/2015/01/07/automated-knitr-in-jekyll.html) by Carl Bouttiger in jan 2015. Yihui Xie, author & maintainer of knitr, has a nice little package out called servr for serving websites from R. It includes a handy jekyll function which streamlines the process of first running knitr on any .Rmd posts before running Jekyll.

[Blog with RStudio, R, RMarkdown, Jekyll and Github](http://andysouth.github.io/blog-setup/)
I wanted to be able to write about R related things without having to copy and paste code, figures or files. I had used Rmarkdown and knitr before so wanted to use them. I have a wordpress site elsewhere that someone helped me set up a couple of years ago with a blog that I’ve never used. Initially I tried seeing if I could create posts using RMarkdown and put them into that wordpress blog. A brief search revealed that was not straightforward and that Jekyll was the way to go.

[Blogging with RStudio and Nikola](http://www.znmeb.mobi/stories/blogging-with-rstudio-and-nikola.html) My goal was to replace my Github Pages Octopress blog with a mobile-first responsive static website / blog authored in R Markdown. The options were

  * Stay with Github Pages / Jekyll / Octopress but author with RStudio,
  * Switch to another static site generator and author with RStudio,
  * Abandon site generators altogether and just author with R Markdown website build tools or knitrBootstrap, and
  * Create a site from the ground up with Bootstrap or Zurb Foundation.

Staying with Github Pages wasn’t a realistic option:

  * The gh-pages branch hack only works for Github,
  * Octopress theming is poorly documented – as far as I can tell the Octopress documentation hasn’t been touched in over three years,
  * Site compilation and deployment are extremely sensitive to Ruby language versioning and use obscure Git-isms, and
  * Octopress isn’t mobile first – it’s just marginally responsive.

[Creating Jekyll blog posts from R](http://www.r-bloggers.com/creating-jekyll-blog-posts-from-r/)
This post is not about getting set up using Jekyll or Jekyll Bootstrap. It’s about establishing a good workflow from R Markdown -> Jekyll Blogpost -> R-Bloggers

[Alfred, RStudio, and Jekyll Workflow](http://blog.eremrah.com/articles/Alfred_RStudio_and_Jekyll/)
There are some sources online showing how this can be done, like this, this, or this but I wanted some easy solutions to automate the workflow. First we need to convert the .Rmd file we write in RStudio to a vanilla .md file in order Jekyll to handle it. Derek Feng has a great make.R file on this Github page. 

[Blog with Knitr and Jekyll](https://jfisher-usgs.github.io/r/2012/07/03/knitr-jekyll/)
The knitr package provides an easy way to embed R code in a Jekyll-Bootstrap blog post. The only required input is an R Markdown source file. The name of the source file used to generate this post is 2012-07-03-knitr-jekyll.Rmd, available here. Steps taken to build this post are as follows...

[Using (R) Markdown, Jekyll, & GitHub for a Website](http://jason.bryer.org/posts/2012-12-10/Markdown_Jekyll_R_for_Blogging.html)
a shell script and R function to convert rmd files to a plain Markdown file that Jekyll can then process. This approach is necessary when using GitHub Pages because user plugins are not supported.


[Dynamic Documents with R and knitr chapter 1-3](https://dl.dropboxusercontent.com/u/19528422/Dynamic_Documents_with_R_and_Knitr_Yihui_Xie_Chap_1-3.pdf) and the [Github repo](https://github.com/yihui/knitr-book/)

